# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JS God
email: jsgod@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am the God of JS. Set upon this planet to imbue my disciples with
  a fountain of arcane knowledge in the language of the Gods. Follow me to
  be enlightened in mystical practices and to dispel the propaganda.
  JS is love; JS is life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ciaranreen.github.io" # the base hostname & protocol for your site
twitter_username: ciaranreen
github_username:  ciaranreen

# Build settings
markdown: kramdown
