# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ciaran Reen
email: ciaran.reen@sky.uk
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer at Sky. I basically made this site to share what I know of the
  beautiful language that is JavaScript with anyone interested. This is going to cover all manner of things!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ciaranreen.github.io" # the base hostname & protocol for your site
twitter_username: ciaranreen
github_username:  ciaranreen

# Build settings
markdown: kramdown
